image: node:latest

stages: 
- build
- test


before_script:
 - cd usr/bin
 - ls
 - cd ../../
 - pwd
 - cd src/juke-app

build:
 stage: build
 script:
  - npm install -g @angular/cli
  - npm run build
 artifacts:
  expire_in: 1 day
  paths:
   - dist/

test:
 stage: test
 script:
 - npm install -g @angular/cli
 - npm run test
 artifacts:
  expire_in: 1 day
  paths:
   - dist/

after_script:
- echo "end CI"