build:

 stages: 
 - build
 - test


 before_script:
 - cd ./src/juke-app/

build:
 script:
  - npm run build
 artifacts:
  expire_in: 1 day
  paths:
   - dist/

test:
 script:
 - npm run test
 artifacts:
  expire_in: 1 day
  paths:
   - dist/

after_script:
- echo "end CI"