image: node:latest

stages: 
- build


before_script:
 - pwd
 - cd src/juke-app

build:
 stage: build
 script:
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular/package.json
  - npm run build
 artifacts:
  expire_in: 1 day
  paths:
   - dist/

after_script:
- echo "end CI"