image: node:latest

stages: 
- build
- test


before_script:
 - pwd
 - cd ./src/juke-app/

build:
 stage: build
 script:
  - npm run build
 artifacts:
  expire_in: 1 day
  paths:
   - dist/

test:
 stage: test
 script:
 - npm run test
 artifacts:
  expire_in: 1 day
  paths:
   - dist/

after_script:
- echo "end CI"